#!/usr/bin/env python3
# Memory tool for the GoofyAddons AI assistant.
#
# Why a script: dates, git checks, moving files and rebuilding the index are easy to get
# wrong by hand (or by an AI). This does them the same way every time.
#
# Memory layout (paths relative to the repo root):
#   .agents/memory/INDEX.md          <- generated by this script; the only file read every task
#   .agents/memory/entries/M-001.md  <- one memory per file, opened only when relevant
#   .agents/memory/archive/M-001.md  <- outdated memories; never loaded, kept for history
#
# Commands:
#   python3 .agents/skills/personalize/scripts/memory.py check [--days 30]   read-only report
#   python3 .agents/skills/personalize/scripts/memory.py next-id             read-only
#   python3 .agents/skills/personalize/scripts/memory.py apply [--touch M-1,M-2] [--confirm M-3]
#                                          [--archive M-4] [--restore M-5] [--recheck M-6]
#       --touch    = "used this session": last_used = today
#       --confirm  = "still true": status active, commit = current HEAD, last_used = today
#       --archive  = move to archive/ (status archived)
#       --restore  = move back from archive/ (status active, commit = HEAD)
#       --recheck  = status recheck (shown in the index so the AI doubts it)
#       Always rebuilds INDEX.md at the end.
#   python3 .agents/skills/personalize/scripts/memory.py index                rebuild INDEX.md only

import datetime
import re
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
FIELD_ORDER = ["id", "type", "summary", "files", "symbols", "commit", "created", "last_used", "status"]
TYPES = {"not-a-bug", "decision", "fact", "correction", "preference"}
STATUSES = {"active", "recheck", "archived"}


# ---------- small helpers: data in -> data out ----------

def git(*args):
    """Runs a git command in the repo and returns its output ('' on failure)."""
    result = subprocess.run(["git", *args], cwd=SCRIPT_DIR, capture_output=True, text=True)
    return result.stdout.strip() if result.returncode == 0 else ""


def repo_root():
    return Path(git("rev-parse", "--show-toplevel") or SCRIPT_DIR.parents[3])


def parse_list(value):
    """'[a, b]' or 'a, b' -> ['a', 'b'];  '[]' or '' -> []"""
    value = value.strip().strip("[]").strip()
    return [item.strip().strip("'\"") for item in value.split(",") if item.strip()]


def read_entry(path):
    """Reads one memory file into a dict: frontmatter fields + 'body' + 'path'.
    Returns None (and the reason) if the file has no valid frontmatter."""
    text = path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---\n?(.*)$", text, re.S)
    if not match:
        return None, f"{path.name}: missing '---' frontmatter block"
    fields = {}
    for line in match.group(1).splitlines():
        if ":" in line and not line.lstrip().startswith("#"):
            key, value = line.split(":", 1)
            fields[key.strip()] = value.strip()
    fields["files"] = parse_list(fields.get("files", ""))
    fields["symbols"] = parse_list(fields.get("symbols", ""))
    fields["body"] = match.group(2)
    fields["path"] = path
    return fields, None


def write_entry(entry):
    """Writes a dict back to its file, keeping the body exactly as it was."""
    lines = ["---"]
    for key in FIELD_ORDER:
        value = entry.get(key, "")
        if key in ("files", "symbols"):
            value = "[" + ", ".join(value) + "]"
        lines.append(f"{key}: {value}")
    lines.append("---")
    entry["path"].write_text("\n".join(lines) + "\n" + entry["body"], encoding="utf-8")


def load_all(memory_dir):
    """Returns (entries, problems) for entries/ and archive/."""
    entries, problems = [], []
    for folder in ("entries", "archive"):
        if not (memory_dir / folder).is_dir():
            continue
        for path in sorted((memory_dir / folder).glob("M-*.md")):
            entry, problem = read_entry(path)
            if problem:
                problems.append(problem)
                continue
            entry["folder"] = folder
            entries.append(entry)
    return entries, problems


def validate(entry):
    """Returns a list of problems with one entry's fields."""
    problems = []
    for key in ("id", "type", "summary", "commit", "created", "last_used", "status"):
        if not entry.get(key):
            problems.append(f"{entry['path'].name}: missing '{key}'")
    if entry.get("type") and entry["type"] not in TYPES:
        problems.append(f"{entry['path'].name}: unknown type '{entry['type']}'")
    if entry.get("status") and entry["status"] not in STATUSES:
        problems.append(f"{entry['path'].name}: unknown status '{entry['status']}'")
    if entry.get("id") and entry["path"].stem != entry["id"]:
        problems.append(f"{entry['path'].name}: file name doesn't match id '{entry['id']}'")
    return problems


def code_changes_since(entry):
    """Commits that touched the entry's files after it was saved (empty list = unchanged)."""
    if not entry["files"]:
        return []
    exists = subprocess.run(["git", "cat-file", "-e", entry["commit"] + "^{commit}"],
                            cwd=SCRIPT_DIR, capture_output=True).returncode == 0
    if not exists:
        return [f"(commit {entry['commit']} not found)"]
    # ":(top)" = path from the repo root (git runs from this script's folder)
    paths = [":(top)" + f for f in entry["files"]]
    out = git("log", "--format=%h %ad %s", "--date=short", f"{entry['commit']}..HEAD", "--", *paths)
    return out.splitlines() if out else []


def days_since(date_text, today):
    try:
        return (today - datetime.date.fromisoformat(date_text)).days
    except ValueError:
        return None


# ---------- commands ----------

def cmd_check(memory_dir, days):
    today = datetime.date.today()
    entries, problems = load_all(memory_dir)
    for entry in entries:
        problems += validate(entry)

    live = [e for e in entries if e["folder"] == "entries"]
    flagged = []
    for entry in live:
        reasons = []
        changes = code_changes_since(entry)
        if changes:
            reasons.append(f"files changed since {entry['commit']}: " + " | ".join(changes[:3])
                           + (f" (+{len(changes) - 3} more)" if len(changes) > 3 else ""))
        unused = days_since(entry.get("last_used", ""), today)
        if unused is not None and unused > days:
            reasons.append(f"not used for {unused} days")
        if entry.get("status") == "recheck":
            reasons.append("already marked recheck")
        if reasons:
            flagged.append((entry, reasons))

    index_path = memory_dir / "INDEX.md"
    expected = build_index(entries)
    if not index_path.exists() or index_path.read_text(encoding="utf-8") != expected:
        problems.append("INDEX.md is out of date -> run: memory.py index")

    print(f"Memory check — {today}  (unused limit: {days} days)")
    print(f"Active/recheck entries: {len(live)}   Archived: {len(entries) - len(live)}")
    print(f"Index size: ~{len(expected) // 4} tokens\n")
    if flagged:
        print("FLAGGED (ask the developer: keep / update / archive):")
        for entry, reasons in flagged:
            print(f"  {entry['id']} [{entry['type']}] {entry['summary']}")
            for reason in reasons:
                print(f"      - {reason}")
    else:
        print("FLAGGED: none")
    print("\nPROBLEMS:" if problems else "\nPROBLEMS: none")
    for problem in problems:
        print(f"  - {problem}")


def cmd_next_id(memory_dir):
    entries, _ = load_all(memory_dir)
    numbers = [int(m.group(1)) for e in entries if (m := re.match(r"M-(\d+)$", e.get("id", "")))]
    print(f"M-{(max(numbers) + 1) if numbers else 1:03d}")


def cmd_apply(memory_dir, args):
    today = datetime.date.today().isoformat()
    head = git("rev-parse", "--short", "HEAD") or "unknown"
    actions = {}
    i = 0
    while i < len(args):
        if args[i] in ("--touch", "--confirm", "--archive", "--restore", "--recheck") and i + 1 < len(args):
            for entry_id in parse_list(args[i + 1]):
                actions[entry_id] = args[i][2:]
            i += 2
        else:
            sys.exit(f"Unknown or incomplete option: {args[i]}")

    entries, _ = load_all(memory_dir)
    by_id = {e.get("id"): e for e in entries}
    for entry_id, action in actions.items():
        entry = by_id.get(entry_id)
        if entry is None:
            print(f"  ! {entry_id}: not found, skipped")
            continue
        if action in ("touch", "confirm"):
            entry["last_used"] = today
        if action in ("confirm", "restore"):
            entry["commit"], entry["status"] = head, "active"
        if action == "recheck":
            entry["status"] = "recheck"
        if action == "archive":
            entry["status"] = "archived"
        target_folder = "archive" if action == "archive" else ("entries" if action == "restore" else entry["folder"])
        old_path = entry["path"]
        entry["path"] = memory_dir / target_folder / old_path.name
        entry["folder"] = target_folder
        write_entry(entry)
        if entry["path"] != old_path:
            old_path.unlink()
        print(f"  {entry_id}: {action} -> {entry['path'].relative_to(memory_dir)}")
    cmd_index(memory_dir)


def build_index(entries):
    """The INDEX.md text. Short on purpose: it's read at the start of every task."""
    live = [e for e in entries if e["folder"] == "entries"]
    lines = [
        "# Memory Index",
        "",
        "<!-- GENERATED by .agents/skills/personalize/scripts/memory.py — don't edit by hand -->",
        "Read at the start of a task. Open `entries/<id>.md` only if its files/symbols/topic match.",
        "Cite as `[mem:<id>]`. `recheck` = may be outdated: doubt it and ask.",
        "",
    ]
    if not live:
        lines.append("_No memories yet. They are created with `/personalize`._")
    else:
        lines.append("| id | type | status | files / symbols | summary | last used |")
        lines.append("| --- | --- | --- | --- | --- | --- |")
        for e in sorted(live, key=lambda e: e.get("id", "")):
            where = ", ".join([Path(f).name for f in e["files"]] + e["symbols"]) or "general"
            lines.append(f"| {e.get('id')} | {e.get('type')} | {e.get('status')} | {where} "
                         f"| {e.get('summary')} | {e.get('last_used')} |")
    return "\n".join(lines) + "\n"


def cmd_index(memory_dir):
    entries, _ = load_all(memory_dir)
    (memory_dir / "INDEX.md").write_text(build_index(entries), encoding="utf-8")
    print(f"INDEX.md rebuilt ({len([e for e in entries if e['folder'] == 'entries'])} live entries)")


def main():
    memory_dir = repo_root() / ".agents" / "memory"
    args = sys.argv[1:] or ["check"]
    if args[0] in ("apply", "index"):  # only the writing commands may create folders
        for folder in ("entries", "archive"):
            (memory_dir / folder).mkdir(parents=True, exist_ok=True)
    if args[0] == "check":
        days = int(args[args.index("--days") + 1]) if "--days" in args else 30
        cmd_check(memory_dir, days)
    elif args[0] == "next-id":
        cmd_next_id(memory_dir)
    elif args[0] == "apply":
        cmd_apply(memory_dir, args[1:])
    elif args[0] == "index":
        cmd_index(memory_dir)
    else:
        sys.exit("usage: memory.py check [--days N] | next-id | apply [--touch/--confirm/--archive/--restore/--recheck IDS] | index")


if __name__ == "__main__":
    main()
